version: "3.9"

services:
  dbt:
    build: .
    working_dir: /usr/app
    volumes:
      - .:/usr/app:delegated
      - /profiles_container.yml:/profiles.yml:ro
    entrypoint: ["dbt"]
    command: ["--help"]
